exp_name: ViT-B-32_8_CART
model: ViT-B-32
pretrained_model: openai
data_location: /workspace/data/
weight_root: /workspace/weight/checkpoints/ViT-B-32
save: /workspace/weight/checkpoints/ViT-B-32
openclip_cachedir: /workspace/weight/checkpoints/ViT-B-32
device: auto
tasks:
- Cars
- DTD
- EuroSAT
- GTSRB
- MNIST
- RESISC45
- SUN397
- SVHN
merge_type: static
merge_method: CART
eval_batch_size: 128
prior: 2.0
initial_rank_ratio: 0.12
half_precision: false
TA_mode: False
external_weight_path: null
