exp_name: ViT-B-32_20_CART
model: ViT-B-32
pretrained_model: openai
data_location: /workspace/data/
weight_root: /workspace/weight/checkpoints/ViT-B-32
save: /workspace/weight/checkpoints/ViT-B-32
openclip_cachedir: /workspace/weight/checkpoints/ViT-B-32
device: auto
tasks:
  - "Cars"
  - "DTD"
  - "EuroSAT"
  - "GTSRB"
  - "MNIST"
  - "RESISC45"
  - "SUN397"
  - "SVHN"
  - "CIFAR100"
  - "STL10"
  - "Flowers102"
  - "OxfordIIITPet"
  - "PCAM"
  - "FER2013"
  - "EMNIST"
  - "CIFAR10"
  - "Food101"
  - "FashionMNIST"
  - "RenderedSST2"
  - "KMNIST"
merge_type: static
merge_method: CART
eval_batch_size: 128
prior: 1.9
initial_rank_ratio: 0.32
half_precision: false
TA_mode: False
external_weight_path: null
